config/routes.rb
Rails.application.routes.draw do
  resources :makes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'inicio' => 'welcome#index'

  get 'imagem' => 'imagem#index'

  resources :makes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/make.rb
class Make < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/imagem_controller.rb
class ImagemController < ApplicationController
	def index
	end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name, :phone, :price, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@teste = "Maquiagens"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imagem_helper.rb
module ImagemHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/imagem/index.html.erb
<%= image_tag("logos/logo4.jpg",  width: '1000px')%>
<%= link_to 'Inicio', "/inicio", :style => 'color: #FF69B4' %>
&nbsp
<%= link_to 'Agendar Atendimento', "/makes/new", :style => 'color: #FF69B4' %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agendamento Maquiagem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% make.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= image_tag("logos/tabela_make.png",  width: '450px')%>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name, id: :make_name %>
  </div>

  <div class="field">
    <%= form.label :Telefone %>
    <%= form.text_field :phone, id: :make_phone %>
  </div>

  <div class="field">
    <%= form.label :TipoDeMake %>
    <%= form.text_field :price, id: :make_price %>
  </div>

  <div class="field">
    <%= form.label :DataDoAtendimento %>
    <%= form.date_select :date, id: :make_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Mostrar', @make, :style => 'color: #FF69B4' %> |
<%= link_to 'Voltar', "/inicio", :style => 'color: #FF69B4' %>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

      <%= image_tag("logos/logo3.png",  width: '450px')%>

<table>
  <thead>
    <tr>
      <th class="Cinza">Nome</th>
      <th class="Cinza">Telefone</th>
      <th class="Cinza">Maquiagem</th>
      <th class="Cinza">Atendimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @makes.each do |make| %>
      <tr>
        <td class="FousOnPanle"><%= make.name %></td>
        <td class="FousOnPanle"><%= make.phone %></td>
        <td class="FousOnPanle"><%= make.price %></td>
        <td class="FousOnPanle"><%= make.date %></td>
        <td ><%= link_to 'Mostrar', make, :style => 'color: #FF69B4' %></td>
        <td ><%= link_to 'Editar', edit_make_path(make), :style => 'color: #FF69B4' %></td>
        <td ><%= link_to 'Deletar', make, method: :delete, data: { confirm: 'Você tem certeza ?' }, :style => 'color: #FF69B4' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td class="FousOnPanle"><%= link_to 'Nova Maquiagem', new_make_path, :style => 'color: #FF69B4' %></td>

app/views/makes/new.html.erb
<%= image_tag("logos/logo5.png",  width: '450px')%>

<%= render 'form', make: @make %>

<%= link_to 'Voltar', "/inicio", :style => 'color: #FF69B4' %>

app/views/makes/show.html.erb
<h1 class = "Confirmado">Atendimento Realizado !</h1>
<h2 class = "Confirmado">Aguarde Confirmação via Celular<h2>
<p id="notice"><%= notice %></p>

<p>
  <strong  class= "FousOnPanle">Nome:</strong>
  <%= @make.name %>
</p>

<p>
  <strong  class= "FousOnPanle">Telefone:</strong>
  <%= @make.phone %>
</p>

<p>
  <strong  class= "FousOnPanle">Maquiagem:</strong>
  <%= @make.price %>
</p>

<p>
  <strong  class= "FousOnPanle">Data:</strong>
  <%= @make.date %>
</p>

<%= link_to 'Editar', edit_make_path(@make), :style => 'color: #FF69B4' %> |
<%= link_to 'Voltar', "/inicio", :style => 'color: #FF69B4' %>

app/views/welcome/index.html.erb
<%= image_tag("logos/logo1.png",  width: '850px')%>

	&#013;
	&#013;
<%= link_to "Marcar Atendimento", "/makes/new", :style => 'color: #FF69B4' %>
	&#013;
	&#013;
<%= link_to 'Fotos de Maquiagens Prontas', "/imagem", :style => 'color: #FF69B4' %>
	&#013;
	&#013;
<%= link_to "Instagram", "https://www.instagram.com/thaismakeup1/", :style => 'color: #FF69B4' %>